apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: reference-app-deny-all
  labels:
    app.kubernetes.io/part-of: reference-apps
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
