apiVersion: v1
kind: Service
metadata:
  name: reference-app
  labels:
    app.kubernetes.io/name: reference-app
    app.kubernetes.io/part-of: reference-apps
spec:
  type: ClusterIP
  selector:
    app: reference-app
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
