apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
labels:
  - pairs:
      app.kubernetes.io/instance: argocd
      owner: platform-team
    includeSelectors: false
    includeTemplates: true
resources:
  - install.yaml
  - app-project.yaml
  - applications/dev.yaml
  - applications/prod.yaml
