apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: APP_NAME
  labels:
    app.kubernetes.io/name: APP_NAME
    app.kubernetes.io/instance: APP_INSTANCE
    app.kubernetes.io/part-of: APP_PART_OF
    environment: ENVIRONMENT
    owner: OWNER
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: APP_HOSTNAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: APP_NAME
                port:
                  number: 80
