apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  labels:
    app.kubernetes.io/name: APP_NAME
    app.kubernetes.io/instance: APP_INSTANCE
    app.kubernetes.io/part-of: APP_PART_OF
    environment: ENVIRONMENT
    owner: OWNER
spec:
  type: ClusterIP
  selector:
    app: APP_NAME
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
