apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app.kubernetes.io/name: apps
    app.kubernetes.io/instance: apps
    app.kubernetes.io/part-of: platform
    owner: platform-team
    platform.aws-platform-starter.io/tier: apps
  annotations:
    platform.aws-platform-starter.io/owner: "platform-team"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/part-of: platform
    owner: platform-team
    platform.aws-platform-starter.io/tier: platform
  annotations:
    platform.aws-platform-starter.io/owner: "platform-team"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/part-of: platform
    owner: platform-team
    platform.aws-platform-starter.io/tier: platform
  annotations:
    platform.aws-platform-starter.io/owner: "platform-team"
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/part-of: platform
    owner: platform-team
    platform.aws-platform-starter.io/tier: platform
  annotations:
    platform.aws-platform-starter.io/owner: "platform-team"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/part-of: platform
    owner: platform-team
    platform.aws-platform-starter.io/tier: platform
  annotations:
    platform.aws-platform-starter.io/owner: "platform-team"
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/instance: logging
    app.kubernetes.io/part-of: platform
    owner: platform-team
    platform.aws-platform-starter.io/tier: platform
  annotations:
    platform.aws-platform-starter.io/owner: "platform-team"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tracing
  labels:
    app.kubernetes.io/name: tracing
    app.kubernetes.io/instance: tracing
    app.kubernetes.io/part-of: platform
    owner: platform-team
    platform.aws-platform-starter.io/tier: platform
  annotations:
    platform.aws-platform-starter.io/owner: "platform-team"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/part-of: platform
    owner: platform-team
    platform.aws-platform-starter.io/tier: platform
  annotations:
    platform.aws-platform-starter.io/owner: "platform-team"
