apiVersion: v1
kind: ResourceQuota
metadata:
  name: apps-baseline
  namespace: apps
  labels:
    app.kubernetes.io/name: apps
    app.kubernetes.io/instance: apps
    app.kubernetes.io/part-of: platform
    owner: platform-team
    platform.aws-platform-starter.io/tier: apps
  annotations:
    platform.aws-platform-starter.io/owner: "platform-team"
spec:
  hard:
    requests.cpu: "6"
    requests.memory: "12Gi"
    limits.cpu: "12"
    limits.memory: "24Gi"
    pods: "80"
    services: "25"
    configmaps: "150"
    secrets: "150"
