apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
labels:
  - pairs:
      app.kubernetes.io/name: demo-app
      app.kubernetes.io/instance: demo-app
      app.kubernetes.io/part-of: demo
      owner: platform-team
    includeSelectors: false
    includeTemplates: true
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdb.yaml
  - hpa.yaml
  - networkpolicy-deny-all.yaml
  - networkpolicy-allow-ingress.yaml
  - networkpolicy-allow-dns.yaml
  - networkpolicy-allow-db-egress.yaml
