apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/instance: platform-prod
    app.kubernetes.io/part-of: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: git@github.com:renanfenrich/aws-platform-starter.git
    targetRevision: main
    path: k8s/clusters/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Prune=false
